version: '3'
services:

  wordrank:
    build: .
    image: wordrank
    container_name: wordrank
    restart: unless-stopped
    user: '1000'
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/db:/src/wordrank/db
