version: '3'
services:

  webdict-python:
    image: webdict-python
    container_name: webdict-python
    restart: unless-stopped
    user: '1000'
    ports:
      - "8080:8000"
    volumes:
      - ./volumes/db:/src/webdict/db
    env_file:
      - ./.env
