version: '3'
services:

  wordrank:
    image: wordrank
    container_name: wordrank
    restart: unless-stopped
    user: '1000'
    ports:
      - "8080:8000"
    volumes:
      - ./volumes/db:/src/wordrank/db
    env_file:
      - ./.env
